- name: installing nginx
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start the service
    ansible.builtin.service:
      name: nginx
      state: started